<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ThreeWa.SshDrive.App</RootNamespace>
    <AssemblyName>3waSshDrive</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\3waSshDrive.Core\3waSshDrive.Core.csproj" />
    <ProjectReference Include="..\3waSshDrive.Sftp\3waSshDrive.Sftp.csproj" />
    <ProjectReference Include="..\3waSshDrive.FileSystem\3waSshDrive.FileSystem.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\runtime\winfsp-2.1.25156-manifest.json"
          Link="runtime\winfsp-2.1.25156-manifest.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
