<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\3waSshDrive.App\3waSshDrive.App.csproj" />
    <ProjectReference Include="..\..\src\3waSshDrive.Core\3waSshDrive.Core.csproj" />
  </ItemGroup>
</Project>
