<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>ThreeWa.SshDrive.Core</RootNamespace>
    <AssemblyName>3waSshDrive.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>
